- hosts: all
  tasks:
    - name: Copy {{ github_sha }} docker image
      copy:
        src: "{{ github_sha }}.tar"
        dest: /tmp/{{ github_sha }}.tar

    - name: Load {{ github_sha }} docker image
      docker_image:
        source: load
        force_source: true
        name: "{{ github_repository_name }}"
        load_path: /tmp/{{ github_sha }}.tar

    - name: start docker container
      docker_container:
        state: started
        image: "{{ github_repository_name }}"
        name: "{{ github_repository_name }}"
        hostname: "{{ github_repository_name }}"
        restart: true
        restart_policy: unless-stopped
        purge_networks: true
        networks_cli_compatible: no
        network_mode: host
        ports:
          - "0.0.0.0:80:80"
